"""Add invitation fields to user model

Revision ID: 202e0dbb4751
Revises: 003_add_audit_logs
Create Date: 2025-11-27 15:03:48.726386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202e0dbb4751'
down_revision = '003_add_audit_logs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_constraint('system_configs_key_key', 'system_configs', type_='unique')
    op.drop_index('ix_system_configs_key', table_name='system_configs')
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.add_column('users', sa.Column('invitation_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('invitation_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('invited_by_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('invitation_accepted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_invitation_token'), 'users', ['invitation_token'], unique=True)
    op.drop_constraint('fk_users_tenant_id', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['invited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_tenant_id', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_invitation_token'), table_name='users')
    op.drop_column('users', 'invitation_accepted_at')
    op.drop_column('users', 'invited_by_id')
    op.drop_column('users', 'invitation_token_expires')
    op.drop_column('users', 'invitation_token')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.create_index('ix_system_configs_key', 'system_configs', ['key'], unique=False)
    op.create_unique_constraint('system_configs_key_key', 'system_configs', ['key'])
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
