"""add_appointments_system

Revision ID: 34fd5a926568
Revises: 005_lead_conversion
Create Date: 2025-12-12 18:05:01.678347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fd5a926568'
down_revision = '005_lead_conversion'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointment_blocks_provider_id'), 'appointment_blocks', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_blocks_provider_id'), table_name='appointment_blocks')
    # ### end Alembic commands ###
