"""add_password_reset_fields

Revision ID: 36ba7c6b15cd
Revises: 4f4ac6e42133
Create Date: 2025-11-18 07:47:42.616678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ba7c6b15cd'
down_revision = '4f4ac6e42133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token_expires')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
