"""Add notifications table

Revision ID: 375f86775a0b
Revises: d7c5ce56df11
Create Date: 2025-11-27 17:30:14.282501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375f86775a0b'
down_revision = 'd7c5ce56df11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notificationtype'), nullable=False, comment='Tipo: info (azul), success (verde), warning (amarillo), error (rojo)'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Título corto de la notificación'),
    sa.Column('message', sa.Text(), nullable=False, comment='Mensaje descriptivo completo de la notificación'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='URL opcional para redirección al hacer click en la notificación'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Indica si la notificación fue leída por el usuario'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='Fecha/hora en que se marcó como leída'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha/hora de creación de la notificación'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
