"""increase_profile_photo_size

Revision ID: 4f4ac6e42133
Revises: 29dba545373c
Create Date: 2025-11-05 10:41:48.295210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4ac6e42133'
down_revision = '29dba545373c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_photo',
                    type_=sa.String(),
                    existing_type=sa.String(500),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_photo',
                    type_=sa.String(500),
                    existing_type=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###
