"""create_email_templates_table

Revision ID: 623713523069
Revises: 36ba7c6b15cd
Create Date: 2025-11-18 08:08:49.675687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623713523069'
down_revision = '36ba7c6b15cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.Enum('PASSWORD_RESET', 'WELCOME', 'NOTIFICATION', name='emailtemplatetype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_templates')
    # ### end Alembic commands ###
