"""Add inventory management system

Revision ID: 86a92e1d7009
Revises: 200895fbb0d0
Create Date: 2025-12-15 16:58:36.052092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a92e1d7009'
down_revision = '200895fbb0d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('unit_type', sa.Enum('PIECES', 'MILLILITERS', 'GRAMS', 'BOXES', 'BOTTLES', 'VIALS', 'AMPOULES', 'TABLETS', 'CAPSULES', 'METERS', name='unittype'), nullable=False),
    sa.Column('unit_size', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('maximum_stock', sa.Integer(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_restock_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('default_quantity', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_inventory_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('IN_PURCHASE', 'IN_DONATION', 'IN_RETURN', 'IN_ADJUSTMENT', 'OUT_USAGE', 'OUT_EXPIRED', 'OUT_DAMAGED', 'OUT_LOSS', 'OUT_ADJUSTMENT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_commercial_objectives_period', table_name='commercial_objectives')
    op.drop_index('ix_commercial_objectives_status', table_name='commercial_objectives')
    op.drop_index('ix_commercial_objectives_type', table_name='commercial_objectives')
    op.add_column('commercial_performance', sa.Column('total_leads_assigned', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_leads_contacted', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_leads_converted', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('conversion_rate', sa.Float(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_appointments_scheduled', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_appointments_completed', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('appointment_show_rate', sa.Float(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_revenue_generated', sa.Float(), nullable=False))
    op.add_column('commercial_performance', sa.Column('average_deal_size', sa.Float(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_calls_made', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_emails_sent', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_meetings_held', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('total_satisfaction_surveys', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('objectives_assigned', sa.Integer(), nullable=False))
    op.add_column('commercial_performance', sa.Column('objectives_completion_rate', sa.Float(), nullable=False))
    op.alter_column('commercial_performance', 'average_satisfaction_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('_commercial_period_uc', 'commercial_performance', type_='unique')
    op.drop_column('commercial_performance', 'objectives_total')
    op.drop_column('commercial_performance', 'qualified_leads')
    op.drop_column('commercial_performance', 'calls_made')
    op.drop_column('commercial_performance', 'performance_score')
    op.drop_column('commercial_performance', 'revenue_generated')
    op.drop_column('commercial_performance', 'appointments_scheduled')
    op.drop_column('commercial_performance', 'appointments_completed')
    op.drop_column('commercial_performance', 'notes')
    op.drop_column('commercial_performance', 'meetings_held')
    op.drop_column('commercial_performance', 'conversions')
    op.drop_column('commercial_performance', 'total_leads')
    op.drop_index('ix_objective_progress_objective_id', table_name='objective_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_objective_progress_objective_id', 'objective_progress', ['objective_id'], unique=False)
    op.add_column('commercial_performance', sa.Column('total_leads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('conversions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('meetings_held', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('commercial_performance', sa.Column('appointments_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('appointments_scheduled', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('revenue_generated', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('performance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('commercial_performance', sa.Column('calls_made', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('qualified_leads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('commercial_performance', sa.Column('objectives_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_unique_constraint('_commercial_period_uc', 'commercial_performance', ['commercial_id', 'period', 'period_start', 'period_end'])
    op.alter_column('commercial_performance', 'average_satisfaction_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('commercial_performance', 'objectives_completion_rate')
    op.drop_column('commercial_performance', 'objectives_assigned')
    op.drop_column('commercial_performance', 'total_satisfaction_surveys')
    op.drop_column('commercial_performance', 'total_meetings_held')
    op.drop_column('commercial_performance', 'total_emails_sent')
    op.drop_column('commercial_performance', 'total_calls_made')
    op.drop_column('commercial_performance', 'average_deal_size')
    op.drop_column('commercial_performance', 'total_revenue_generated')
    op.drop_column('commercial_performance', 'appointment_show_rate')
    op.drop_column('commercial_performance', 'total_appointments_completed')
    op.drop_column('commercial_performance', 'total_appointments_scheduled')
    op.drop_column('commercial_performance', 'conversion_rate')
    op.drop_column('commercial_performance', 'total_leads_converted')
    op.drop_column('commercial_performance', 'total_leads_contacted')
    op.drop_column('commercial_performance', 'total_leads_assigned')
    op.create_index('ix_commercial_objectives_type', 'commercial_objectives', ['type'], unique=False)
    op.create_index('ix_commercial_objectives_status', 'commercial_objectives', ['status'], unique=False)
    op.create_index('ix_commercial_objectives_period', 'commercial_objectives', ['period'], unique=False)
    op.drop_table('inventory_movements')
    op.drop_table('appointment_inventory_usage')
    op.drop_table('service_products')
    op.drop_table('inventory_alerts')
    op.drop_table('inventory_products')
    op.drop_table('inventory_categories')
    # ### end Alembic commands ###
