"""add_smtp_config_to_tenant

Revision ID: 91d91178aba2
Revises: bd306d1b2209
Create Date: 2025-12-28 20:06:49.511961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d91178aba2'
down_revision = 'bd306d1b2209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('smtp_username', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('smtp_password_encrypted', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('smtp_from_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('smtp_from_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('smtp_use_tls', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('smtp_use_ssl', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenants', sa.Column('smtp_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'smtp_enabled')
    op.drop_column('tenants', 'smtp_use_ssl')
    op.drop_column('tenants', 'smtp_use_tls')
    op.drop_column('tenants', 'smtp_from_name')
    op.drop_column('tenants', 'smtp_from_email')
    op.drop_column('tenants', 'smtp_password_encrypted')
    op.drop_column('tenants', 'smtp_username')
    op.drop_column('tenants', 'smtp_port')
    op.drop_column('tenants', 'smtp_host')
    op.drop_column('tenants', 'website')
    # ### end Alembic commands ###
