"""Add patient role to UserRole enum

Revision ID: 9e4b78e2a31f
Revises: 86a92e1d7009
Create Date: 2025-12-15 21:31:23.182434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4b78e2a31f'
down_revision = '86a92e1d7009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
