"""Fix metadata field name conflict

Revision ID: 9f0a6042a6de
Revises: bed63fc805dd
Create Date: 2025-12-15 10:46:46.165938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0a6042a6de'
down_revision = 'bed63fc805dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
