"""Make service_id optional in appointments

Revision ID: c4cbf38a4915
Revises: 34fd5a926568
Create Date: 2025-12-12 20:33:14.539483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cbf38a4915'
down_revision = '34fd5a926568'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'service_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'service_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
