"""Add user_invitation email template type

Revision ID: d7c5ce56df11
Revises: 202e0dbb4751
Create Date: 2025-11-27 15:04:37.389384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c5ce56df11'
down_revision = '202e0dbb4751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
