# Pydantic schemas will be defined here
from app.schemas.user import (
    User,
    UserCreate,
    UserUpdate,
    UserLogin,
    Token,
    TokenData,
    UserInDB,
    UserWithTenant,
    TenantAdminCreate,
    ChangePassword,
    ClientCreate,
)

from app.schemas.tenant import (
    Tenant,
    TenantUpdate,
    TenantInDB,
    TenantList,
    TenantWithStats,
    TenantCreateWithAdmin,
)

# Lead Management System Schemas
from app.schemas.lead import (
    Lead,
    LeadCreate,
    LeadUpdate,
    LeadInDB,
    LeadAssign,
    LeadStatusUpdate,
    LeadInteraction,
    LeadInteractionCreate,
    LeadInteractionUpdate,
    LeadAssignment,
    LeadAssignmentCreate,
    LeadFilters,
    LeadStats,
    LeadFunnelStats,
    LeadSourcePerformance,
    LeadListResponse,
    LeadToPatientConversion,
    LeadConversionResponse,
)

from app.schemas.service import (
    Service,
    ServiceCreate,
    ServiceUpdate,
    ServiceInDB,
    ServiceDetailed,
    ServiceCategory,
    ServiceCategoryCreate,
    ServiceCategoryUpdate,
    ServicePackage,
    ServicePackageCreate,
    ServicePackageUpdate,
    ServiceProvider,
    ServiceProviderCreate,
    ServiceProviderUpdate,
    ServiceFilters,
    ServiceStats,
    ServicePerformance,
    ServiceListResponse,
)

from app.schemas.appointment import (
    Appointment,
    AppointmentCreate,
    AppointmentUpdate,
    AppointmentInDB,
    AppointmentDetailed,
    AppointmentStatusUpdate,
    AppointmentReschedule,
    AppointmentCancel,
    AppointmentCheckIn,
    AppointmentCheckOut,
    AppointmentAvailability,
    AppointmentAvailabilityCreate,
    AppointmentAvailabilityUpdate,
    AppointmentBlock,
    AppointmentBlockCreate,
    AppointmentBlockUpdate,
    AppointmentFilters,
    AvailabilityQuery,
    AvailabilityResponse,
    AvailableSlot,
    AppointmentStats,
    ProviderScheduleStats,
)

from app.schemas.treatment import (
    Treatment,
    TreatmentCreate,
    TreatmentUpdate,
    TreatmentInDB,
    TreatmentDetailed,
    TreatmentStatusUpdate,
    TreatmentConsentUpdate,
    TreatmentPhotosUpdate,
    TreatmentSession,
    TreatmentSessionCreate,
    TreatmentSessionUpdate,
    MedicalRecord,
    MedicalRecordCreate,
    MedicalRecordUpdate,
    TreatmentFilters,
    TreatmentStats,
    ProviderTreatmentStats,
)

__all__ = [
    # User schemas
    "User",
    "UserCreate",
    "UserUpdate",
    "UserLogin",
    "Token",
    "TokenData",
    "UserInDB",
    "UserWithTenant",
    "TenantAdminCreate",
    "ChangePassword",
    "ClientCreate",
    
    # Tenant schemas
    "Tenant",
    "TenantUpdate",
    "TenantInDB",
    "TenantList",
    "TenantWithStats",
    "TenantCreateWithAdmin",
    
    # Lead Management Schemas
    "Lead",
    "LeadCreate",
    "LeadUpdate",
    "LeadInDB",
    "LeadAssign",
    "LeadStatusUpdate",
    "LeadInteraction",
    "LeadInteractionCreate",
    "LeadInteractionUpdate",
    "LeadAssignment",
    "LeadAssignmentCreate",
    "LeadFilters",
    "LeadStats",
    "LeadFunnelStats",
    "LeadSourcePerformance",
    "LeadListResponse",
    "LeadToPatientConversion",
    "LeadConversionResponse",
    
    # Service Schemas
    "Service",
    "ServiceCreate",
    "ServiceUpdate",
    "ServiceInDB",
    "ServiceDetailed",
    "ServiceCategory",
    "ServiceCategoryCreate",
    "ServiceCategoryUpdate",
    "ServicePackage",
    "ServicePackageCreate",
    "ServicePackageUpdate",
    "ServiceProvider",
    "ServiceProviderCreate",
    "ServiceProviderUpdate",
    "ServiceFilters",
    "ServiceStats",
    "ServicePerformance",
    "ServiceListResponse",
    
    # Appointment Schemas
    "Appointment",
    "AppointmentCreate",
    "AppointmentUpdate",
    "AppointmentInDB",
    "AppointmentDetailed",
    "AppointmentStatusUpdate",
    "AppointmentReschedule",
    "AppointmentCancel",
    "AppointmentCheckIn",
    "AppointmentCheckOut",
    "AppointmentAvailability",
    "AppointmentAvailabilityCreate",
    "AppointmentAvailabilityUpdate",
    "AppointmentBlock",
    "AppointmentBlockCreate",
    "AppointmentBlockUpdate",
    "AppointmentFilters",
    "AvailabilityQuery",
    "AvailabilityResponse",
    "AvailableSlot",
    "AppointmentStats",
    "ProviderScheduleStats",
    
    # Treatment Schemas
    "Treatment",
    "TreatmentCreate",
    "TreatmentUpdate",
    "TreatmentInDB",
    "TreatmentDetailed",
    "TreatmentStatusUpdate",
    "TreatmentConsentUpdate",
    "TreatmentPhotosUpdate",
    "TreatmentSession",
    "TreatmentSessionCreate",
    "TreatmentSessionUpdate",
    "MedicalRecord",
    "MedicalRecordCreate",
    "MedicalRecordUpdate",
    "TreatmentFilters",
    "TreatmentStats",
    "ProviderTreatmentStats",
]
